### ISSUE TITLE
RuntimeError: npm dependencies failed to install

### ISSUE THREAD

**Issue by astrojuanlu** [matplotlib/ipympl#153]
I'm trying to install jupyter-matplotlib on Python 3.7 (tried 3.7.4 and 3.7.5) on Linux to no avail:

```
(_test_ipympl37_4) juanlu@voyager:/tmp$ jupyter labextension install @jupyter-widgets/jupyterlab-manager
Building jupyterlab assets (build:prod:minimize)
(_test_ipympl37_4) juanlu@voyager:/tmp$ jupyter labextension install jupyter-matplotlib
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-2q4l3z34.log
```

And the log file says:

```
Yarn configuration loaded.
Node v12.13.0

> /snap/bin/npm pack jupyter-matplotlib
npm notice 
npm notice 📦  jupyter-matplotlib@0.4.2
npm notice === Tarball Contents === 
npm notice 896B    package.json         
npm notice 161B    README.md            
npm notice 2.5kB   webpack.config.js    
npm notice 585.8kB dist/index.js        
npm notice 722.1kB dist/index.js.map    
npm notice 455B    src/embed.js         
npm notice 182B    src/index.js         
npm notice 434B    src/lab_extension.js 
npm notice 435B    src/mpl_widget.css   
npm notice 15.1kB  src/mpl_widget.js    
npm notice 309B    src/nb_extension.js  
npm notice 520B    src/nb_index.js      
npm notice 5.7kB   src/toolbar_widget.js
npm notice 1.4kB   src/utils.js         
npm notice === Tarball Details === 
npm notice name:          jupyter-matplotlib                      
npm notice version:       0.4.2                                   
npm notice filename:      jupyter-matplotlib-0.4.2.tgz            
npm notice package size:  233.5 kB                                
npm notice unpacked size: 1.3 MB                                  
npm notice shasum:        8a12ce8fe612a71887dbe77a4b713139a4acf319
npm notice integrity:     sha512-m+OICpR9BPEMS[...]Lp43Pf+AToBvg==
npm notice total files:   14                                      
npm notice 
jupyter-matplotlib-0.4.2.tgz

Yarn configuration loaded.
Node v12.13.0

Building jupyterlab assets (build:prod:minimize)
> node /home/juanlu/.pyenv/versions/3.7.4/envs/_test_ipympl37_4/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
error /home/juanlu/.pyenv/versions/3.7.4/envs/_test_ipympl37_4/share/jupyter/lab/staging/node_modules/jupyter-matplotlib: Command failed.
Exit code: 243
Command: npm run build
Arguments: 
Directory: /home/juanlu/.pyenv/versions/3.7.4/envs/_test_ipympl37_4/share/jupyter/lab/staging/node_modules/jupyter-matplotlib
Output:

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

npm dependencies failed to install
Traceback (most recent call last):

  File "/home/juanlu/.pyenv/versions/3.7.4/envs/_test_ipympl37_4/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/juanlu/.pyenv/versions/3.7.4/envs/_test_ipympl37_4/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/home/juanlu/.pyenv/versions/3.7.4/envs/_test_ipympl37_4/lib/python3.7/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

  File "/home/juanlu/.pyenv/versions/3.7.4/envs/_test_ipympl37_4/lib/python3.7/site-packages/jupyterlab/commands.py", line 660, in build
    raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install

Exiting application: jupyter
```

However, when I go to the directory and run `npm run build`, it seems to work:

```
(_test_ipympl37_4) juanlu@voyager:/tmp$ cd /home/juanlu/.pyenv/versions/3.7.4/envs/_test_ipympl37_4/share/jupyter/lab/staging/node_modules/jupyter-matplotlib
(_test_ipympl37_4) juanlu@voyager:~/.pyenv/versions/3.7.4/envs/_test_ipympl37_4/share/jupyter/lab/staging/node_modules/jupyter-matplotlib$ npm run build
npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/2525/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> jupyter-matplotlib@0.4.2 build /home/juanlu/.pyenv/versions/3.7.4/envs/_test_ipympl37_4/share/jupyter/lab/staging/node_modules/jupyter-matplotlib
> webpack

Hash: b54991fbda573d3949ef35c21bce2f6c453f93240c455b1bcdb0bb54d7dc
Version: webpack 4.41.2
Child
    Hash: b54991fbda573d3949ef
    Time: 1449ms
    Built at: 11/19/2019 4:35:02 AM
           Asset     Size  Chunks             Chunk Names
    extension.js  1.1 KiB       0  [emitted]  main
    Entrypoint main = extension.js
    [0] ./src/nb_extension.js 309 bytes {0} [built]
    
    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
Child
    Hash: 35c21bce2f6c453f9324
    Time: 5092ms
    Built at: 11/19/2019 4:35:05 AM
           Asset      Size  Chunks                   Chunk Names
        index.js  89.9 KiB       0  [emitted]        main
    index.js.map   742 KiB       0  [emitted] [dev]  main
    Entrypoint main = index.js index.js.map
     [0] ./package.json 896 bytes {0} [built]
     [1] external "@jupyter-widgets/base" 42 bytes {0} [built]
     [2] ../lodash/lodash.js 528 KiB {0} [built]
     [3] ./src/nb_index.js 520 bytes {0} [built]
     [4] ./src/index.js 182 bytes {0} [built]
     [5] ./src/mpl_widget.js 14.8 KiB {0} [built]
     [6] ../webpack/buildin/global.js 472 bytes {0} [built]
     [7] ../webpack/buildin/module.js 497 bytes {0} [built]
     [8] ./src/toolbar_widget.js 5.55 KiB {0} [built]
     [9] ./src/utils.js 1.36 KiB {0} [built]
    [10] ./src/mpl_widget.css 1.06 KiB {0} [built]
    [11] ./node_modules/css-loader/dist/cjs.js!./src/mpl_widget.css 600 bytes {0} [built]
    [13] ../style-loader/lib/addStyles.js 10.2 KiB {0} [built]
    [14] ../style-loader/lib/urls.js 2.94 KiB {0} [built]
        + 1 hidden module
    
    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
Child
    Hash: 0c455b1bcdb0bb54d7dc
    Time: 4818ms
    Built at: 11/19/2019 4:35:05 AM
           Asset      Size  Chunks                   Chunk Names
        index.js  89.8 KiB       0  [emitted]        main
    index.js.map   741 KiB       0  [emitted] [dev]  main
    Entrypoint main = index.js index.js.map
     [0] ./package.json 896 bytes {0} [built]
     [1] external "@jupyter-widgets/base" 42 bytes {0} [built]
     [2] ../lodash/lodash.js 528 KiB {0} [built]
     [3] ./src/embed.js 455 bytes {0} [built]
     [4] ./src/mpl_widget.js 14.8 KiB {0} [built]
     [5] ../webpack/buildin/global.js 472 bytes {0} [built]
     [6] ../webpack/buildin/module.js 497 bytes {0} [built]
     [7] ./src/toolbar_widget.js 5.55 KiB {0} [built]
     [8] ./src/utils.js 1.36 KiB {0} [built]
     [9] ./src/mpl_widget.css 1.06 KiB {0} [built]
    [10] ./node_modules/css-loader/dist/cjs.js!./src/mpl_widget.css 600 bytes {0} [built]
    [12] ../style-loader/lib/addStyles.js 10.2 KiB {0} [built]
    [13] ../style-loader/lib/urls.js 2.94 KiB {0} [built]
        + 1 hidden module
    
    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
(_test_ipympl37_4) juanlu@voyager:~/.pyenv/versions/3.7.4/envs/_test_ipympl37_4/share/jupyter/lab/staging/node_modules/jupyter-matplotlib$ echo $?
0
```

**Comment by Juanlu001** [comment]
Fixed by removing the `snap` installed `node` and using the `apt` one.

**Comment by KiyarashFarivar** [comment]
I get the same error "npm dependencies failed to install" did not understand how you solved it. can you give more details ? @astrojuanlu

**Comment by martinRenou** [comment]
How did you install nodejs? Can you try updating it?

**Comment by KiyarashFarivar** [comment]
@martinRenou  I installed Nodejs just like the installation guide:
> conda install -c conda-forge nodejs
I think since I did it right now I wouldn't need to update ?

**Comment by KiyarashFarivar** [comment]
BTW this is my log file:

> Node v6.13.1

Yarn configuration loaded.
> /home/kiyarash/anaconda3/bin/npm pack @jupyter-widgets/jupyterlab-manager
jupyter-widgets-jupyterlab-manager-2.0.0.tgz

Node v6.13.1

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node /home/kiyarash/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error marked@0.8.0: The engine "node" is incompatible with this module. Expected version ">= 8.16.2". Got "6.13.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

npm dependencies failed to install
Traceback (most recent call last):

  File "/home/kiyarash/anaconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/kiyarash/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/home/kiyarash/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

  File "/home/kiyarash/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 652, in build
    raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install

Exiting application: jupyter

**Comment by martinRenou** [comment]
Yes it should be fine then.

What does `which npm` say?

**Comment by KiyarashFarivar** [comment]
I think this is the problem :

> error marked@0.8.0: The engine "node" is incompatible with this module. Expected version ">= 8.16.2". Got "6.13.1"

**Comment by martinRenou** [comment]
Yes, your Node version looks outdated.

What does `which npm` say?

**Comment by KiyarashFarivar** [comment]
/home/kiyarash/anaconda3/bin/npm

**Comment by martinRenou** [comment]
Super weird. I don't know what's happening here.

> The engine "node" is incompatible with this module. Expected version ">= 8.16.2". Got "6.13.1"

This is wrong. Latest `npm` is 6.14.4

**Comment by martinRenou** [comment]
Do you get this error when doing
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib
```
?
Or is this when trying to run another command?

**Comment by KiyarashFarivar** [comment]
yes it happens when I run the "jupyter labextension install" command you mentioned.

**Comment by martinRenou** [comment]
I've got no clue what's happening here. I'd recommend starting again from a clean environment.

**Comment by KiyarashFarivar** [comment]
Ok I will try that when I have time. Thnx for your help.

**Comment by martinRenou** [comment]
I feel like yarn is not picking the right npm when trying to install the labextension

**Comment by cvanelteren** [comment]
same error as @sjoycode. Updating nodejs fixed the build issue but still getting the error `Javascript Error: IPython is not defined`

**Comment by Deniz93** [comment]
> > @martinRenou I installed Nodejs just like the installation guide:
> > > conda install -c conda-forge nodejs
> > 
> > 
> > I think since I did it right now I wouldn't need to update ?
> 
> Interestingly, `conda list` shows me a node version 6.13.1 as mentioned in the error log. I applied `conda update nodejs` and things started working. Also, I executed `jupyter lab build` as instructed in [this](https://github.com/jupyter-widgets/ipywidgets/issues/2220#issuecomment-473365591) comment before invoking the jupyter lab.

this worked for me

**Comment by martinRenou** [comment]
Yes it looks like the issue comes from `conda` installing an old version of nodejs. We need a decently recent nodejs version for the labextension to build correctly.
