### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by recmo** [matplotlib/ipympl#456]
## Describe the issue

```
%matplotlib widget
import matplotlib.pyplot as plt

plt.plot([0,1],[0,1])
```

results in

```
Error displaying widget: model not found
```

The javascript console shows:

```
Could not instantiate widget
Error: Could not create a model.
Uncaught (in promise) Error: Module jupyter-matplotlib, semver range ^0.10.5 is not registered as a widget module
```

## Versions

```
 3.9.12 (main, Mar 26 2022, 15:44:31) 
[Clang 13.1.6 (clang-1316.0.21.2)]
ipympl version: 0.8.8
Selected Jupyter core packages...
IPython          : 8.2.0
ipykernel        : 6.12.1
ipywidgets       : 7.7.0
jupyter_client   : 7.2.1
jupyter_core     : 4.9.2
jupyter_server   : 1.16.0
jupyterlab       : 3.3.2
nbclient         : 0.5.13
nbconvert        : 6.4.5
nbformat         : 5.3.0
notebook         : 6.4.10
qtconsole        : not installed
traitlets        : 5.1.1
Known nbextensions:
  config dir: /Users/remco/.jupyter/nbconfig
    notebook section
      toggle_all_line_numbers/main  enabled 
      - Validating: OK
      equation-numbering/main  enabled 
      - Validating: OK
      toc2/main  enabled 
      - Validating: OK
      collapsible_headings/main disabled
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      scroll_down/main  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      contrib_nbextensions_help_item/main  enabled 
      - Validating: OK
    tree section
      nbextensions_configurator/tree_tab/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      jupyter-matplotlib/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
JupyterLab v3.3.2
/usr/local/share/jupyter/labextensions
        jupyter-matplotlib v0.10.1 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/share/jupyter/lab


The following source extensions are overshadowed by older prebuilt extensions:
    jupyter-matplotlib
```

**Comment by recmo** [comment]
I've tried removing `ipympl` and `jupyter-matplotlib`, but I can not remove the latter:

```
❯ jupyter labextension uninstall jupyter-matplotlib       
JupyterLab cannot uninstall jupyter-matplotlib since it was installed outside of JupyterLab. Use the same method used to install this extension to uninstall this extension.
```

```
❯ pip uninstall jupyter-matplotlib                        
WARNING: Skipping jupyter-matplotlib as it is not installed.
```

I have no idea how to remove `jupyter-matplotlib`.

**Comment by recmo** [comment]
Ok, this worked:

```
❯ rm -r /usr/local/share/jupyter/labextensions/jupyter-matplotlib`
❯ jupyter labextension uninstall jupyter-matplotlib       
Uninstalling jupyter-matplotlib from /opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/share/jupyter/lab/extensions
Building jupyterlab assets (production, minimized)
❯ jupyter labextension uninstall jupyter-matplotlib
No labextension named "jupyter-matplotlib" installed
❯ jupyter labextension list
JupyterLab v3.3.2
/usr/local/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)
```

But I'm still getting the same error.

**Comment by recmo** [comment]
After running
```
❯ jupyter labextension install jupyter-matplotlib
Building jupyterlab assets (production, minimized)
```
It now works, but this feels wrong since the Readme says just running `pip ipympl` should be enough.

**Comment by recmo** [comment]
Now the extension manager shows a 500 error and `jupyter lab` logs the following on the console:

```
[W 2022-04-10 13:01:26.315 LabApp] Unhandled error
[E 2022-04-10 13:01:26.315 LabApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0"
    }
[E 2022-04-10 13:01:26.315 LabApp] 500 GET /lab/api/extensions?1649588486296 (127.0.0.1) 15.13ms referer=http://localhost:8888/lab
[E 2022-04-10 13:01:28.917 ServerApp] Uncaught exception GET /lab/api/extensions?1649588488897 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/lab/api/extensions?1649588488897', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/homebrew/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 252, in get
        extensions = yield self.manager.list_extensions()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/homebrew/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 119, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/homebrew/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 190, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/homebrew/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 252, in get
        extensions = yield self.manager.list_extensions()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/homebrew/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 119, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/homebrew/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 190, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/homebrew/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 252, in get
        extensions = yield self.manager.list_extensions()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/homebrew/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 119, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/homebrew/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 190, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/homebrew/lib/python3.9/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 221, in _load_outdated
        data = yield self.executor.submit(
      File "/opt/homebrew/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
        return self.__get_result()
      File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
        raise self._exception
      File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/homebrew/lib/python3.9/site-packages/jupyterlab/commands.py", line 565, in get_latest_compatible_package_versions
        return handler.latest_compatible_package_versions(names)
      File "/opt/homebrew/lib/python3.9/site-packages/jupyterlab/commands.py", line 1871, in latest_compatible_package_versions
        raise ValueError(msg % keys)
    ValueError: "['jupyter-matplotlib@0.10.5']" is not a valid npm package
[W 2022-04-10 13:01:28.918 LabApp] Unhandled error
[E 2022-04-10 13:01:28.919 LabApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0"
    }
[E 2022-04-10 13:01:28.919 LabApp] 500 GET /lab/api/extensions?1649588488897 (127.0.0.1) 16.96ms referer=http://localhost:8888/lab
```

**Comment by rcpeene** [comment]
I am using ipympl within an environment on binder and am getting this problem. [Here](https://github.com/matplotlib/ipympl/issues/473) some workarounds are discussed, but these are not viable for me, as I don't have direct control over the jupyterlab configuration in binder. Is there a fix for this within ipyml?

**Comment by rcpeene** [comment]
Any updates here?

**Comment by martinRenou** [comment]
Can you share the output of `jupyter labextension list`? Please note that it's always better to open your own issue while filling the issue form that asks these informations, those endless issue threads with multiple issue cases are difficult to handle.

**Comment by rcpeene** [comment]
Here's the output of `jupyter labextension list`:
```
JupyterLab v3.4.8
/srv/conda/envs/notebook/share/jupyter/labextensions
        jupyter-offlinenotebook v0.2.2 enabled OK
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        jupyter-webrtc v0.6.0 enabled OK
        jupyterlab-datawidgets v7.1.2 enabled OK
        jupyter-threejs v2.4.0 enabled OK (python, pythreejs)
        ipydatagrid v1.1.14 enabled OK
        jupyter-matplotlib v0.11.2 enabled OK
        jupyter-vuetify v1.8.4 enabled OK
        ipyvolume v0.6.0-alpha.10 enabled OK
        jupyterlab-plotly v5.11.0 enabled OK
        bqplot v0.5.37 enabled OK (python, bqplot)
        jupyter-vue v1.8.0 enabled OK
        ipytree v0.2.2 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.1.1 enabled OK (python, jupyterlab_widgets)
        @jupyter-server/resource-usage v0.6.3 enabled OK (python, jupyter-resource-usage)

Other labextensions (built into JupyterLab)
   app dir: /srv/conda/envs/notebook/share/jupyter/lab
```

**Comment by martinRenou** [comment]
Do you have an error in the JavaScript console?

**Comment by rcpeene** [comment]
Hmmm, running `pip uninstall ipywebrtc` doesn't seem to be the fix.
